---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_karabiner: true

dockutil_install: true
configure_dock: true
dockitems_remove: 
  - "Launchpad"
  - "TV"
  - "Podcasts"
  - "App Store"
  - "Music"
  - "Photos"
  - "Calendar"
  - "Maps"
  - "FaceTime"
  - "News"
  - "Freeform"
  - "Contacts"
  - "Mail"
  - "Safari"
  - "Reminders"
  - "iPhone Mirroring"
  - "Notes"
  - "Messages"
  - "System Settings"
dockitems_persist: 
  - name: "Dia"
    path: "/Applications/Dia.app"
    pos: 1
  - name: "Messages"
    path: "/Applications/Messages.app"
    pos: 2
  - name: "Notion Calendar"
    path: "/Applications/Notion Calendar.app"
    pos: 3
  - name: "Obsidian"
    path: "/Applications/Obsidian.app"
    pos: 4
  - name: "Warp"
    path: "/Applications/Warp.app"
    pos: 5
  - name: "Cursor"
    path: "/Applications/Cursor.app"
    pos: 6
  - name: "iPhone Mirroring"
    path: "/Applications/iPhone Mirroring.app"
    pos: 7
  - name: "System Settings"
    path: "/Applications/System Settings.app"
    pos: 8

homebrew_taps:
  - creativeprojects/tap
homebrew_installed_packages:
  - bat
  - oven-sh/bun/bun
  - chruby
  - deno
  - eza
  - fd
  - fzf
  - gh 
  - git
  - go
  - httpie
  - keeper-commander
  - kubectl
  - kubectx
  - neovim
  - node@22
  - nvm
  - pipx
  - pulumi
  - pyenv
  - ripgrep
  - restic
  - resticprofile 
  - tmux
  - tree
  - uv
  - watch
  - yt-dlp
  - zoxide
  - zsh
  - zsh-vi-mode

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - arc
  - chatgpt
  - cursor
  - discord
  - docker
  - font-fira-code
  - google-cloud-sdk
  - karabiner-elements
  - keeper-password-manager
  - native-access
  - notion
  - notion-calendar
  - obsidian
  - slack
  - telegram
  - thebrowsercompany-dia
  - spotify
  - warp
  - superwhisper
  - zoom 

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: ["corepack", "vercel"]
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: [omzsh.yml]
