---
- name: Check if deno exists
  command: "{{ ansible_env.HOME }}/.deno/bin/deno --version"
  register: deno_check
  ignore_errors: true
  tags: [deno]

- name: Install deno
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://deno.land/install.sh)"
  when: not ansible_check_mode and deno_check.rc != 0
  tags: [deno]