---
- name: Create Karabiner-Elements configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory
    mode: '0755'
  tags: [karabiner]

- name: Create Karabiner-Elements configuration file
  tags: [karabiner]
  copy:
    dest: "{{ ansible_env.HOME }}/.config/karabiner/karabiner.json"
    mode: '0644'
    content: |
      {
        "profiles": [
          {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": [
              {
                "from": {
                  "key_code": "caps_lock"
                },
                "to": {
                  "key_code": "escape"
                }
              }
            ]
          },
          "complex_modifications": [
            {
              "parameters": {
                "simultaneous_threshold_milliseconds": 130
              },
              "title": "Vi Mode (rev 5)",
              "rules": [
                {
                  "description": "Vi Mode [S as Trigger Key]",
                  "manipulators": [
                    {
                      "type": "basic",
                      "from": {
                        "key_code": "j",
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "key_code": "down_arrow",
                          "modifiers": []
                        }
                      ],
                      "conditions": [
                        {
                          "type": "variable_if",
                          "name": "vi_mode",
                          "value": 1
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "simultaneous": [
                          {
                            "key_code": "s"
                          },
                          {
                            "key_code": "j"
                          }
                        ],
                        "simultaneous_options": {
                          "key_down_order": "strict",
                          "key_up_order": "strict_inverse",
                          "detect_key_down_uninterruptedly": true,
                          "to_after_key_up": [
                            {
                              "set_variable": {
                                "name": "vi_mode",
                                "value": 0
                              }
                            }
                          ]
                        },
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "set_variable": {
                            "name": "vi_mode",
                            "value": 1
                          }
                        },
                        {
                          "key_code": "down_arrow",
                          "modifiers": []
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "key_code": "k",
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "key_code": "up_arrow",
                          "modifiers": []
                        }
                      ],
                      "conditions": [
                        {
                          "type": "variable_if",
                          "name": "vi_mode",
                          "value": 1
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "simultaneous": [
                          {
                            "key_code": "s"
                          },
                          {
                            "key_code": "k"
                          }
                        ],
                        "simultaneous_options": {
                          "key_down_order": "strict",
                          "key_up_order": "strict_inverse",
                          "detect_key_down_uninterruptedly": true,
                          "to_after_key_up": [
                            {
                              "set_variable": {
                                "name": "vi_mode",
                                "value": 0
                              }
                            }
                          ]
                        },
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "set_variable": {
                            "name": "vi_mode",
                            "value": 1
                          }
                        },
                        {
                          "key_code": "up_arrow",
                          "modifiers": []
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "key_code": "h",
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "key_code": "left_arrow",
                          "modifiers": []
                        }
                      ],
                      "conditions": [
                        {
                          "type": "variable_if",
                          "name": "vi_mode",
                          "value": 1
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "simultaneous": [
                          {
                            "key_code": "s"
                          },
                          {
                            "key_code": "h"
                          }
                        ],
                        "simultaneous_options": {
                          "key_down_order": "strict",
                          "key_up_order": "strict_inverse",
                          "detect_key_down_uninterruptedly": true,
                          "to_after_key_up": [
                            {
                              "set_variable": {
                                "name": "vi_mode",
                                "value": 0
                              }
                            }
                          ]
                        },
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "set_variable": {
                            "name": "vi_mode",
                            "value": 1
                          }
                        },
                        {
                          "key_code": "left_arrow",
                          "modifiers": []
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "key_code": "l",
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "key_code": "right_arrow",
                          "modifiers": []
                        }
                      ],
                      "conditions": [
                        {
                          "type": "variable_if",
                          "name": "vi_mode",
                          "value": 1
                        }
                      ]
                    },
                    {
                      "type": "basic",
                      "from": {
                        "simultaneous": [
                          {
                            "key_code": "s"
                          },
                          {
                            "key_code": "l"
                          }
                        ],
                        "simultaneous_options": {
                          "key_down_order": "strict",
                          "key_up_order": "strict_inverse",
                          "detect_key_down_uninterruptedly": true,
                          "to_after_key_up": [
                            {
                              "set_variable": {
                                "name": "vi_mode",
                                "value": 0
                              }
                            }
                          ]
                        },
                        "modifiers": {
                          "optional": [
                            "any"
                          ]
                        }
                      },
                      "to": [
                        {
                          "set_variable": {
                            "name": "vi_mode",
                            "value": 1
                          }
                        },
                        {
                          "key_code": "right_arrow",
                          "modifiers": []
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        ]
      }

- name: Ensure Karabiner-Elements is running
  command: open -a Karabiner-Elements
  changed_when: false
  tags: [karabiner]
