---
- name: Create Karabiner-Elements configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory
    mode: '0755'

- name: Create Karabiner-Elements configuration file
  copy:
    dest: "{{ ansible_env.HOME }}/.config/karabiner/karabiner.json"
    content: |
      {
        "profiles": [
          {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": [
              {
                "from": {
                  "key_code": "caps_lock"
                },
                "to": {
                  "key_code": "escape"
                }
              }
            ]
          }
        ]
      }
    mode: '0644'

- name: Ensure Karabiner-Elements is running
  command: open -a Karabiner-Elements
  changed_when: false 