---
- name: Configure trackpad settings
  command: "{{ item }}"
  with_items:
    # Enable tap to click
    - defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
    - /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
    
    # Set tracking speed (0-3, where 3 is fastest)
    - defaults write -g com.apple.trackpad.scaling -float 1.5
    
    # Set click pressure (0-1, where 1 is lightest)
    - defaults write -g com.apple.trackpad.forceClick -float 0.5
  changed_when: false
  tags: ['trackpad'] 